### ISSUE TITLE
How do you make a field in row clickable

### ISSUE THREAD

**Issue by jozcar** [ianwitherow/react-filterable-table#1]
Thanks for writing this component, I was able to quickly set up.  what would be the best way to make on field in a row clickable?

**Comment by ianwitherow** [comment]
Hey,

I think what you're looking for is the `render` prop on a field. I still need to put up a demo using it, but there's a code example at the bottom of the readme. Basically you'd create a function that accepts a `props` parameter, and returns what you'd like to render in that field.

Quick example:


```
function renderJobField(props) {
    return <a href={'https://www.google.com/?q=' + props.value}>{props.value}</a>;
}
```

Then use that function in your `field`:

```
let fields = [
   ...
   { name: 'job', displayName: "Job", render: renderJobField }
   ...
]
```

So then that Job field in the table will use that function to render its contents, in this case a link to search a job title on Google.

Check out the bottom of the readme for more details, and to see what that `props` object passed to the render function looks like.

**Comment by jozcar** [comment]
thanks for the tip.

**Comment by kczx3** [comment]
How would this work if the table was filterable?  Seeing as the cell's contents can be clicked to filter on that value in that column.

**Comment by ianwitherow** [comment]
If you use a render function for the cell, it'll override the 'exactFilterable' property. However, if you want to use a render function and still have all or part of it filter when clicked, you can use a function called `addExactFilter` that gets passed in with that `props` object to the render function.

I just realized this isn't documented at all so I'll have to do that, but here's an example of how that'd work:

```
// The render function used on a field
function renderSandwich(props) {
	const {
		value,
		record,
		field,
		addExactFilter
	} = props;

	/*
	 * addExactFilter accepts:
	 * value: The value to filter on
	 * fieldname: The name of the field (the object property of the data record)
	 * name (optional): The name to display in the filter. It'll just use fieldname if left out.
	 */

	return (
		<span onClick={() => addExactFilter(props.value, field.name, field.displayName)}>
			{value}
		</span>
	);

}
```

Let me know if you have any questions!
