### ISSUE TITLE
How to sort by date

### ISSUE THREAD

**Issue by jozcar** [ianwitherow/react-filterable-table#10]
# How to Sort By Date
Do you have any suggestion about sorting by date, currently it is sorting by string. 

Thanks,

**Comment by ianwitherow** [comment]
You should cast the strings to date objects first, like `new Date(dateString)`.
You can either do this before setting the `data` prop, or in the `onDataReceived` function.

**Comment by jozcar** [comment]
Thanks for the suggestion.
