### ISSUE TITLE
CSS issue

### ISSUE THREAD

**Issue by pushkar1701** [ianwitherow/react-filterable-table#11]
For some unknown reasons, the CSS is not included in my project. Could you please confirm the exact steps to take to use your module with create-react-app.

**Comment by ianwitherow** [comment]
Hey, make sure to include the css file from the /dist folder:

```<link href="/node_modules/react-filterable-table/dist/style.css" rel="stylesheet" />```

**Comment by Akumar96** [comment]
Didn't link with gatsby.js? The pagination is coming on my screen like a bullet list and won't go inline.

**Comment by GaganBhat** [comment]
It doesn't appear to work with React.js either, the table itself functions, but the CSS doesn't seem to apply.
