### ISSUE TITLE
How to use addExactFilter

### ISSUE THREAD

**Issue by projectdev-user** [ianwitherow/react-filterable-table#16]
addExactFilter cannot be used for custom filters? Is there a any demo/example code

**Comment by ianwitherow** [comment]
Here's an example of when I used it for displaying a list of sales reps. This allowed me to list multiple people in the same table cell, but allows the user to click on each one to add a filter with their name.

This is a render function for a field:

```javascript
RepList(props) {
	const reps = props.value;
	const { addExactFilter, field } = props;

	return reps.length === 0
		? <span className="empty">{field.emptyDisplay}</span>
		: reps.map((rep, q) => {
			return (
				<span key={q}>
					<span onClick={() => addExactFilter(rep, "Reps", "Rep")} className="filterable text-nowrap">
						{rep}
					</span>
					{q < reps.length - 1 ? ", " : ""}
				</span>
			);
		});
}
```


`addExactFilter(value, fieldname, name = fieldname)`
`value` is the value you'd like to filter on
`fieldname` is the name of the field that the filter is applied to
`name` is what's displayed on the page when filtering (defaults to the field name)
