### ISSUE TITLE
Please provide an example of sortFieldName

### ISSUE THREAD

**Issue by t7m** [ianwitherow/react-filterable-table#24]
There's no example and the description is vague. I don't want my prices to sort like this:
1
10
11
12
2
3
4

I'd actually expect a function to get a sort value, similar to render(), but that's not what you have. How does sortFieldName work? Where's a working example?

**Comment by ianwitherow** [comment]
You're more than welcome to create a pull request!

`sortFieldName` is used to tell it which field it should perform the sort on. In this case, you'd want a field made up of floats instead of strings so that it sorts correctly. Ideally you'd get it from your data source, e.g. an API call. If you can't, then I'd just create one in the `onDataReceived` function. Example:

```javascript
class MyComponent extends React.Component {
	constructor(props) {
		super(props);
		this.fields = [
			{ name: "item_description", displayName: "Item", sortable: true, tdClassName: "text-nowrap" },
			{ name: "qty", displayName: "Quantity", sortable: true },
			{ name: "price_string", displayName: "Price", sortFieldName: "price_sort", sortable: true },
			// Note the "price_sort" value for the sortFieldName. We'll populate that in onDataReceived.
		];
	}

	onDataReceived(records) {
		records.length > 0 && records.forEach(r => {
			// Convert string value to float
			const price = +r.price_string.replace(/[\$,+]/g, "");
			r.price_sort = price; // Here we're using `price_sort` which is what we used for the `sortFieldName` earlier
		});
	}


	render() {
		return (
			<FilterableTable
				initialSort="item_description"
				initialSortDir={false}
				dataEndpoint="/api/products"
				fields={this.fields}
				onDataReceived={this.onDataReceived}
				serverErrorMessage={<div className="alert alert-danger">Server error!</div>}
				noRecordsMessage={<div className="alert alert-info">No products found.</div>}
				noFilteredRecordsMessage={<div className="alert alert-info">No matches found.</div>}
			/>
		);
	}
}
```

**Comment by t7m** [comment]
I see. Seems odd to create a new field but I guess that's how you set it up.

**Comment by ianwitherow** [comment]
Cool man. This is just a component I use at work that I thought could be useful for other people so I threw it on here. I'm not a company, not making money off of it, just trying to be helpful. You can fork it and do whatever you want.

**Comment by t7m** [comment]
It's a decent tool, enjoying it!

In hindsight, I think adding the extra sorting column is probably better for performance. Might be better to create that extra column at the beginning, rather than to run functions on every field while sorting. Makes sense! It's just that the documentation wasn't clear to me. Thanks for the help
