### ISSUE TITLE
Table with buttons/url

### ISSUE THREAD

**Issue by ishmeetg** [ianwitherow/react-filterable-table#4]
Is there some way to use buttons with onclick events in the table rows? Or have a URL in the table row content?

**Comment by ianwitherow** [comment]
Yeah, you'll want to use the render property on your field object.
`{ name: 'someName', ..., render: yourRenderFunction }`

You give it a function which returns what you want to render in that cell; plain text, react object, etc. The function receives various parameters related to the data it should display. Check out my response on this [issue here](https://github.com/ianwitherow/react-filterable-table/issues/1): https://github.com/ianwitherow/react-filterable-table/issues/1

And there's some documentation about how the render function works here:
https://github.com/ianwitherow/react-filterable-table#example-using-a-render-function

Hope this helps!

**Comment by ishmeetg** [comment]
Thanks a lot for clarifying that!
