### ISSUE TITLE
removeExactFilter

### ISSUE THREAD

**Issue by AshotN** [ianwitherow/react-filterable-table#7]
there is currently no way to programmatically remove a filter... can this be added?

**Comment by ianwitherow** [comment]
I could expose a function to the `render` functions where you could pass in a fieldname to remove its respective filter, would that work? Or can you give me an example of how you'd like to use it?

Thanks!

**Comment by AshotN** [comment]
Frankly I'd like it if each field has a visible Boolean that could be updated via the state. 

		let fields = [
			{ name: 'type', displayName: "Order Type", visible: this.state.nameVisible },
		];

**Comment by ianwitherow** [comment]
Fields do have a `visible` prop:

https://github.com/ianwitherow/react-filterable-table#field-props

> visible - bool - Whether or not the field is visible.

I'm not sure if you can update a specific field's visible property _directly_ like that, but you could put the `fields` array in your state, then update the specific field's visible prop within that to have it update on the fly. Let me know if I'm off base with what you're asking.

**Comment by AshotN** [comment]
I don't remember if I tried it, I'll try it all again and give you something more concrete and we can work on it from there... thanks 👍

**Comment by ianwitherow** [comment]
I'm going to close this issue, but feel free to re-open it if you feel the need.
